[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Removendo o plugin do Netlify para Next.js, já que estamos usando exportação estática
# [[plugins]]
# package = "@netlify/plugin-nextjs"
